### ISSUE TITLE
User Role dropdown is not aligned in DeleteUserMeta Module

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#683] opened 2019-10-22 05:44 UTC
Please refer attached screenshot:
![Screenshot from 2019-10-21 12-05-43](https://user-images.githubusercontent.com/38071735/67261163-22b82300-f4bd-11e9-8a95-b1e865158ce0.png)

**Comment by sudar** [comment] 2019-10-30 23:30
Duplicate of #682 , closing now.

**Closed as completed by sudar** 2019-10-30 23:30 UTC
